site_name: semver-check
repo_url: https://github.com/makanu/semver-check
site_url: https://makanu.github.io/semver-check
site_description: This project publishes a simple webserver which validates input against semver.
site_author: Matti Kaupenjohann
edit_uri: edit/main/docs/
repo_name: makanu/semver-check
copyright: Maintained by <a href="https://makanu.com">makanu</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [semver_check]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/makanu/semver-check
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/semver-check

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
